switch.unknown_node_106_switch:
  ignored: false
  polling_intensity: 1
binary_sensor.linear_wadwaz1_doorwindow_sensor_sensor:
  ignored: true
  polling_intensity: 0
binary_sensor.linear_wadwaz1_doorwindow_sensor_sensor_2:
  ignored: true
  polling_intensity: 0
binary_sensor.linear_wapirz1_motion_sensor_sensor:
  ignored: true
  polling_intensity: 0
sensor.vision_zp3111_multisensor_4in1_emergency:
  ignored: true
  polling_intensity: 0
sensor.vision_zp3111_multisensor_4in1_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.vision_zp3111_multisensor_4in1_system:
  ignored: true
  polling_intensity: 0
binary_sensor.vision_zp3111_multisensor_4in1_sensor:
  ignored: true
  polling_intensity: 0
sensor.lava_lamp_two_exporting_2:
  ignored: true
  polling_intensity: 0
sensor.lava_lamp_two_energy_2:
  ignored: true
  polling_intensity: 0
sensor.aeotec_dsc06106_smart_energy_switch_interval_2:
  ignored: true
  polling_intensity: 0
sensor.lava_lamp_two_interval:
  ignored: true
  polling_intensity: 0
sensor.lava_lamp_two_power_4:
  ignored: true
  polling_intensity: 0
sensor.lava_lamp_two_power_2:
  ignored: true
  polling_intensity: 0
sensor.lava_lamp_two_previous_reading_2:
  ignored: true
  polling_intensity: 0
sensor.lava_lamp_two_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.office_lamp_two_energy:
  ignored: true
  polling_intensity: 0
sensor.office_lamp_two_exporting:
  ignored: true
  polling_intensity: 0
sensor.aeotec_dsc06106_smart_energy_switch_interval:
  ignored: true
  polling_intensity: 0
sensor.office_lamp_two_interval:
  ignored: true
  polling_intensity: 0
sensor.office_lamp_two_power_3:
  ignored: true
  polling_intensity: 0
sensor.office_lamp_two_power:
  ignored: true
  polling_intensity: 0
sensor.office_lamp_two_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.aeotec_dsc06106_smart_energy_switch_previous_reading:
  ignored: true
  polling_intensity: 0
sensor.office_window_sensor_burglar:
  ignored: true
  polling_intensity: 0
sensor.office_window_sensor_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.living_room_window_sensor_burglar:
  ignored: true
  polling_intensity: 0
sensor.living_room_window_sensor_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.vision_zp3111_multisensor_4in1_homehealth:
  ignored: true
  polling_intensity: 0
binary_sensor.vision_zp3111_multisensor_4in1_sensor_2:
  ignored: true
  polling_intensity: 0
sensor.motion_sensor_attic_emergency:
  ignored: true
  polling_intensity: 0
sensor.garage_door_opener_remote_controller_access_control:
  ignored: true
  polling_intensity: 0
sensor.garage_door_opener_remote_controller_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.garage_door_opener_remote_controller_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.garage_door_opener_remote_controller_burglar:
  ignored: true
  polling_intensity: 0
binary_sensor.garage_door_opener_remote_controller_sensor:
  ignored: true
  polling_intensity: 0
sensor.garage_door_opener_remote_controller_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.vision_zp3111_multisensor_4in1_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.vision_zp3111_multisensor_4in1_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.water_sensor_attic_flood:
  ignored: true
  polling_intensity: 0
sensor.water_sensor_attic_sourcenodeid:
  ignored: true
  polling_intensity: 0
